spring:
  thymeleaf:
    mode: LEGACYHTML5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.159.242:3306/answer?characterEncoding=utf-8&useSSL=false
    username: root
    password: 
    useSSl: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085
